### PR TITLE
feat(bin): adds binary packages with deploy to s3

### PR DESCRIPTION
**Pull request by Fluidbyte**
- Adds [`pkg`](https://github.com/zeit/pkg) to build node6 bins
- Creates build scripts for Mac, Linux and Windows
- Simplifies update notifier so it doesn't give `npm` upgrade instructions
- Adds deploy scripting to `.travis.yml`

### CODE REVIEW

**Comment by davezuko** [comment]
Don't see anything that sticks out, but I'm also going to look at how `pkg` works since it's foreign to me.

**Comment by Fluidbyte** [comment]
If you want to test the bin, just load up dind with:

```
docker run -it -v /var/run/docker.sock:/var/run/docker.sock ubuntu:latest sh -c "apt-get update ; apt-get install docker.io -y ; bash"
```

Then `npm run build:linux && alias devlab=$PWD/bin/linux/devlab`

**Comment by stephen-ta** [comment]
Fancy! screen shot 2017-05-20 at 10 08 50 pm

**Comment by stephen-ta** [comment]
So I pulled this branch onto my local Mac, and ran `npm run test` which gave 112 passing tests. 

Yet when I tried the commands you gave above (actually ran `npm run build` first, then started over with just linux), the last part didn't work. Here's the output after trying again with just the linux build...

```
Stephens-MacBook-Pro:DevLab stephenbelcher$ npm run build:linux

> devlab@3.11.1 build:linux /Users/stephenbelcher/Projects/DevLab
> pkg . -t node6-linux --out-dir=./bin/linux

> pkg@3.0.4
Stephens-MacBook-Pro:DevLab stephenbelcher$ docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/app -w /app docker
/app # alias devlab=$PWD/bin/linux/devlab
/app # devlab -v
sh: /app/bin/linux/devlab: not found
/app # lab -v
sh: lab: not found
/app # npm run test
sh: npm: not found
/app # ls
LICENSE.txt   bin           demo.gif      node_modules  src
README.md     coverage      index.js      package.json  test
/app # npm install
sh: npm: not found
```

**Comment by Fluidbyte** [comment]
That's weird, I'm having the same problem now. Trying to figure it out.

**Comment by Fluidbyte** [comment]
Incompatible version of C on the `docker` container. You can use Ubuntu via the following for step 2:

```
docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock -v $PWD:/app -w /app ubuntu sh -c "apt-get update && apt-get install docker.io -y && bash"
```

Updated comments and docs

**Comment by stephen-ta** [comment]
That worked! 🍪 (Curious, as I saw your stragglers commit, are you shifting away from any `lab` usage and going strictly `devlab` now?)

**Comment by TomFrost** [comment]
Oh my god I love this.

**Comment by Fluidbyte** [comment]
@stephen-ta; yes, I think (after a LOT of thought) that we should nix the "alias" and let users alias as they want. The command should be the same as the binary, and while I will leave it in the `package.json` for now I want to transition the docs first, then we'll eventually remove it in a major release.

**Pull request merged**
