### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by jordandenison**
Implement unit tests for index.js and refactor index.js to hide private method functionality and update to Babel 6.

### CODE REVIEW

**Comment by Fluidbyte** [comment]
Looks great! I'd like to have one more person take a look before we merge and I'll probably go through it one more time.

**Comment by Fluidbyte** [comment]
We'd also like to try to match our internal conventions, so if you'd like to add it in we're using Babel6 with the `es2015` preset. Then we use `isparta@^4.0.0`. Our `test` task runs coverage and linting and our `mocha` just runs the tests (applicable entries from `package.json > scripts` below)

```
    "test": "npm run lint && npm run cover",
    "mocha": "babel-node node_modules/.bin/_mocha",
    "cover": "babel-node node_modules/isparta/bin/isparta cover node_modules/mocha/bin/_mocha",
    "lint": "eslint . --fix",
    "prepublish": "npm test && npm run build"
```

We use `mocha.opts` in our `/test` dir as well:

```
--require test/setup.js
--recursive
--timeout 5000
```

Totally up to you, I can add this in once we merge.

**Comment by jordandenison** [comment]
process.exit was only being replaced and spied on instead of stubbed in the config spec which was causing the build to pass even if tests failed - now that that has been corrected, the build is failing now that a few of the services tests are failing.  Also now that we are on Babel 6 I don't think proxyquire is working anymore for some reason as "const core" is coming up as undefined in index.spec.js now.

**Comment by Fluidbyte** [comment]
It _looks_ like an issue with the changes to `export default` in Babel6, if you log out `core` you'll see nothing is in the root of the object, there's now a `default` property and everything is in that.

I can log out `core.default.run` and see the function but haven't had a chance to go much further.

**Comment by Fluidbyte** [comment]
😄

**Comment by Fluidbyte** [comment]
Looks great! :accept:

**Pull request merged**
