### PR TITLE
fix(services): change silence to false to see error log

### LINKED ISSUE #41: Dump Logs from Failing Service Start
Currently when a service startup fails or a link cannot be completed the process simply exits with no explanation of the error. Need to dump any error messages so problem can be triaged and corrected.

### PR DESCRIPTION
**Pull request by Atsman**
fixes #41

### CODE REVIEW

**Comment by Atsman** [comment]
Hello,

I use your project and first thing i notice is that there is no output in console if something wrong.
For local development i fixed that in global node_modules, by just changing silent argument to false.
I don't know, maybe there is exists more elegant solution to this. What do you think?

Best regards,
Aleh

**Comment by Fluidbyte** [comment]
We recently reworked a lot of the tool to cut down on verbosity of the internal actions. I've been meaning to address this; my preferred approach would be to collect the output of failed services and output only that. Simply outputting the `proc.run` for the services will also output the id's of all the service containers which is what I'd specifically like to avoid.

**Comment by Atsman** [comment]
So for now I suggest to have a flag like --debug, using which user able to see full output. I like your idea, but do not understand how to implement it. Will review code and think tomorrow.

**Comment by davezuko** [comment]
Also may be wise to consider using https://www.npmjs.com/package/debug.

**Comment by Fluidbyte** [comment]
This PR would really only help if the service container doesn't exist. If you start a service that fails it will still just show the sha for that container, the container will just exit immediately.

What would be more beneficial would be a `--debug` option that would run a tail on the logs so you could see why a container failed (internal to that service).

The issue I see with that though is if you're tailing all logs through a spawned process they wouldn't have any context, i.e. all the logs would just be outputting simultaneously for the multiple services.

**Comment by Fluidbyte** [comment]
After thinking about this, I'd like to propose a different approach. We're about to merge #55 which includes output of any services that failed to stop successfully. I'd like to add this to the service start process as well.

The output from docker is limited in detail (like I mentioned before, that's what logs give you). So my thought is to be more verbose about what service(s) failed to start by returning the id's in the error output. Then you at least have visibility on what failed and can investigate why.

Closing this PR. Tracking the fix for this in #41

**Pull request closed without merging**
